scenario="frac2B_1.00_no1B";
pcl_file = "frac2B_1.00_no1B.pcl";

#scenario_type = fMRI_emulation; 
#scan_period = 800; 
scenario_type = fMRI;  
pulses_per_scan = 1; 
pulse_code = 1; 
default_text_color = 255, 255, 255; 
default_font ="Arial"; 
default_font_size = 54;
write_codes = false;
no_logfile = false;
#active_buttons = 4;
#button_codes = 1,2,3,4;
#active_buttons = 3;
#button_codes = 1,2,3;
active_buttons = 2;
button_codes = 1,2;


begin;

box { height = 2000; width = 2000; color = 0,0,0; } back;
bitmap { filename="mask_Fix_xhair.jpg"; } xhair;
#text { caption="0"; font_size=22; font_color=0,0,0;} debug;
text { caption="0"; font_size=22; font_color=0,0,0;} debug;

#bitmap { filename="3back_formB1_img_0.jpg"; } instr_0;
#bitmap { filename="3back_formB1_img_1.jpg"; } instr_1;
#bitmap { filename="3back_formB1_img_2.jpg"; } instr_2;
#bitmap { filename="3back_formB1_img_3.jpg"; } instr_3;
bitmap { filename="2back_img_0.jpg"; } instr_0;
#bitmap { filename="2back_img_1.jpg"; } instr_1;
bitmap { filename="2back_img_2.jpg"; } instr_2;

bitmap { filename="spacer.jpg"; } null;

bitmap { filename="fnb_formB_01.jpg"; } picB;
bitmap { filename="fnb_formB_02.jpg"; } picC;
bitmap { filename="fnb_formB_03.jpg"; } picD;
bitmap { filename="fnb_formB_04.jpg"; } picF;
bitmap { filename="fnb_formB_05.jpg"; } picG;
bitmap { filename="fnb_formB_06.jpg"; } picH;
bitmap { filename="fnb_formB_07.jpg"; } picJ;
bitmap { filename="fnb_formB_08.jpg"; } picK;
bitmap { filename="fnb_formB_09.jpg"; } picL;
bitmap { filename="fnb_formB_10.jpg"; } picM;
bitmap { filename="fnb_formB_11.jpg"; } picN;
bitmap { filename="fnb_formB_12.jpg"; } picP;
bitmap { filename="fnb_formB_13.jpg"; } picQ;
bitmap { filename="fnb_formB_14.jpg"; } picR;
bitmap { filename="fnb_formB_15.jpg"; } picS;
bitmap { filename="fnb_formB_16.jpg"; } picT;
bitmap { filename="fnb_formB_17.jpg"; } picV;
bitmap { filename="fnb_formB_18.jpg"; } picW;
bitmap { filename="fnb_formB_19.jpg"; } picX;
bitmap { filename="fnb_formB_20.jpg"; } picZ;

## DEFINE CROSSHAIR ##
bitmap { filename="crosshair.jpg"; } cross;


array {

#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	#bitmap xhair;
	### CUT OFF
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap picJ;
	bitmap cross; 
	bitmap cross; 
	bitmap picM;
	bitmap cross; 
	bitmap cross; 
	bitmap picQ;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picL;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picR;
	bitmap cross; 
	bitmap cross;
	bitmap picH;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picK;
	bitmap cross; 
	bitmap cross;
	bitmap picJ;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picW;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap picR;
#	bitmap picT;
#	bitmap picS;
#	bitmap picS;
#	bitmap picR;
#	bitmap picH;
#	bitmap picH;
#	bitmap picW;
#	bitmap picC;
#	bitmap picC;
#	bitmap picL;
#	bitmap picP;
#	bitmap picR;
#	bitmap picP;
#	bitmap picM;
#	bitmap picM;
#	bitmap picM;
#	bitmap picB;
#	bitmap picW;
#	bitmap picK;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap picH;
	bitmap cross; 
	bitmap cross;
	bitmap picW;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picQ;
	bitmap cross; 
	bitmap cross;
	bitmap picP;
	bitmap cross; 
	bitmap cross;
	bitmap picQ;
	bitmap cross; 
	bitmap cross;
	bitmap picM;
	bitmap cross; 
	bitmap cross;
	bitmap picT;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picT;
	bitmap cross; 
	bitmap cross;
	bitmap picH;
	bitmap cross; 
	bitmap cross;
	bitmap picT;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picK;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap picK;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap picC;
	#bitmap picP;
	#bitmap picK;
	#bitmap picC;
	#bitmap picD;
	#bitmap picV;
	#bitmap picV;
	#bitmap picD;
	#bitmap picS;
	#bitmap picQ;
	#bitmap picD;
	#bitmap picC;
	#bitmap picT;
	#bitmap picJ;
	#bitmap picB;
	#bitmap picT;
	#bitmap picW;
	#bitmap picC;
	#bitmap picM;
	#bitmap picW;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap picM;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
	bitmap picM;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picR;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picC;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picM;
	bitmap cross; 
	bitmap cross;
	bitmap picW;
	bitmap cross; 
	bitmap cross;
	bitmap picL;
	bitmap cross; 
	bitmap cross;
	bitmap picR;
	bitmap cross; 
	bitmap cross;
	bitmap picL;
	bitmap cross; 
	bitmap cross;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picR;
	bitmap cross; 
	bitmap cross;
	bitmap picD;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picL;
	bitmap cross; 
	bitmap cross;
	bitmap picC;
	bitmap cross; 
	bitmap cross;
	bitmap picK;
	bitmap cross; 
	bitmap cross;
	bitmap picP;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picJ;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
	bitmap picW;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picH;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picH;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap picF;
	#bitmap picT;
	#bitmap picS;
	#bitmap picF;
	#bitmap picL;
	#bitmap picT;
	#bitmap picD;
	#bitmap picL;
	#bitmap picW;
	#bitmap picK;
	#bitmap picS;
	#bitmap picB;
	#bitmap picK;
	#bitmap picJ;
	#bitmap picQ;
	#bitmap picQ;
	#bitmap picJ;
	#bitmap picT;
	#bitmap picG;
	#bitmap picJ;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap picH;
#	bitmap picW;
#	bitmap picD;
#	bitmap picD;
#	bitmap picD;
#	bitmap picS;
#	bitmap picS;
#	bitmap picL;
#	bitmap picB;
#	bitmap picT;
#	bitmap picT;
#	bitmap picQ;
#	bitmap picZ;
#	bitmap picL;
#	bitmap picR;
#	bitmap picR;
#	bitmap picF;
#	bitmap picG;
#	bitmap picB;
#	bitmap picM;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap instr_3;
	#bitmap picR;
	#bitmap picQ;
	#bitmap picQ;
	#bitmap picR;
	#bitmap picC;
	#bitmap picZ;
	#bitmap picM;
	#bitmap picJ;
	#bitmap picZ;
	#bitmap picT;
	#bitmap picH;
	#bitmap picZ;
	#bitmap picV;
	#bitmap picD;
	#bitmap picH;
	#bitmap picV;
	#bitmap picK;
	#bitmap picD;
	#bitmap picP;
	#bitmap picK;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap instr_2;
	bitmap picJ;
	bitmap cross; 
	bitmap cross;
	bitmap picF;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picS;
	bitmap cross; 
	bitmap cross;
	bitmap picR;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picM;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
	bitmap picQ;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picQ;
	bitmap cross; 
	bitmap cross;
	bitmap picN;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
	bitmap picT;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap instr_1;
#	bitmap picR;
#	bitmap picH;
#	bitmap picS;
#	bitmap picS;
#	bitmap picG;
#	bitmap picT;
#	bitmap picT;
#	bitmap picR;
#	bitmap picP;
#	bitmap picC;
#	bitmap picC;
#	bitmap picM;
#	bitmap picJ;
#	bitmap picK;
#	bitmap picR;
#	bitmap picL;
#	bitmap picL;
#	bitmap picL;
#	bitmap picF;
#	bitmap picM;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap instr_0;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picP;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picL;
	bitmap cross; 
	bitmap cross;
	bitmap picP;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picZ;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
	bitmap picB;
	bitmap cross; 
	bitmap cross;
	bitmap picV;
	bitmap cross; 
	bitmap cross;
	bitmap picG;
	bitmap cross; 
	bitmap cross;
	bitmap picJ;
	bitmap cross; 
	bitmap cross;
	bitmap picX;
	bitmap cross; 
	bitmap cross;
	bitmap picP;
	bitmap cross; 
	bitmap cross;
	bitmap picD;
	bitmap cross; 
	bitmap cross;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair;
	bitmap xhair; 
	bitmap xhair;

} pic_ary;

picture {
	default_code="default";
	box back;
	x=0; y=0;
	text debug;
	x=-480; y=350;
} default;

picture {
	default_code="solid";
	bitmap xhair;
	x=0; y=10;
	text debug;
	x=-480; y=350;
} solid;

trial { picture default; } default_trial;

trial {

	trial_type = fixed;
	clear_active_stimuli = true;

	picture solid;
	time=0;
	
} solid_trial;

trial {

	trial_type = fixed;
	clear_active_stimuli = true;

	picture {
		default_code="pic1";
		bitmap xhair;
		x=0; y=10;
		text debug;
		x=-480; y=350;
	} pic1;
	time=0;
	#duration = 800; ## removed because causing flicker between crosshair slides ##

} trial1;


