---
title: "RSAS_score"
output: html_document
date: "2026-01-21"
---

```{r score RSAS}
# Code script to score the Revised Social Anhedonia Scale - Chapman et al. (1976)
# https://doi.org/10.1037/0021-843X.85.4.374
# Scoring instructions: Items that need to be are reverse scored so that the more anhedonic response corresponds to 1 for each individual item. Then, both the sum of the individual item responses and the average of these responses are calculated for summary measures. A higher score indicates greater anhedonia.

# Load required packages (optional, for tidy syntax)
library(dplyr)
library (readr)

# Load data
RSAS <- read_tsv("/Users/bsevchik/projects/EF_clinical/self-report/scale_csvs_Jan/separate_tsvs/rsas.tsv")

# Compute total scores for each individual participant
rev_items <- c(
  "soc_anhed_4", "soc_anhed_9", "soc_anhed_11", "soc_anhed_12", "soc_anhed_13", "soc_anhed_14"
)
keep_items <- c("soc_anhed_1", "soc_anhed_2", "soc_anhed_3", "soc_anhed_5", "soc_anhed_6", "soc_anhed_7", "soc_anhed_8", "soc_anhed_10", "soc_anhed_15", rev_items)

RSAS <- RSAS %>%
  mutate(across(all_of(keep_items), as.numeric)) %>%
  mutate(across(all_of(rev_items), ~ 1 - .x)) %>%
  mutate(
    rsas_total_score = rowSums(across(all_of(keep_items)), na.rm = TRUE),
    rsas_average_score = rowMeans(across(all_of(keep_items)), na.rm = TRUE)
  )
write_tsv(RSAS,"/Users/bsevchik/projects/EF_clinical/self-report/scale_csvs_Jan/final_scored_tsvs/rsas.tsv", na = "n/a")
```
``` {r RSAS distribution}
library(ggplot2)
library(dplyr)

RSAS %>%
  ggplot(aes(x = rsas_total_score)) +
  geom_histogram(bins = 20) +
  labs(x = "RSAS total score (sum of 15 items)", y = "Number of sessions",
       title = "Distribution of RSAS total scores")

RSAS %>%
  ggplot(aes(x = rsas_average_score)) +
  geom_histogram(bins = 20) +
  labs(x = "RSAS average score", y = "Number of sessions",
       title = "Distribution of RSAS average scores")

```
