#!/usr/bin/env python3
"""
Check EF task log coverage against BIDS sessions in a dataset and optionally
recover missing logs from an external data dump when possible.

This script:
- Discovers EF fractal n-back logs under a Flywheel-style folder tree
  (<bblid>/SESSIONS/<scanid>/ACQUISITIONS/*/FILES/*-frac2B_1.00_no1B.log)
- Uses a session map TSV (bblid, scanid, session_id[, timestamp]) to convert
  discovered (bblid, scanid) pairs into (bblid, session_id) pairs with logs
- Scans a BIDS dataset directory for subjects and reads each
  sub-<bblid>/sub-<bblid>_sessions.tsv to collect available session_id values
- Compares log-derived subject/session pairs vs BIDS sessions and prints a report
- For sessions missing logs, optionally searches an external "datadump" under
  SCANNER_TASK_T1/T2/T3 for files matching <bblid>*-frac2B_1.00_no1B.log,
  validates the log's written date (second line) against the session map
  timestamp (date-only comparison), and, if matching, copies the log into a
  RECOVERED acquisition under the Flywheel tree
"""

import argparse
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare subjects/sessions with EF logs vs BIDS sessions in a dataset"
        )
    )
    parser.add_argument(
        "--logs-dir",
        required=True,
        type=Path,
        help=(
            "Flywheel SUBJECTS directory containing <bblid>/SESSIONS/<scanid> with logs"
        ),
    )
    parser.add_argument(
        "--session-map",
        required=True,
        type=Path,
        help=(
            "TSV generated by generate_session_map.py (columns: bblid, scanid, session_id)"
        ),
    )
    parser.add_argument(
        "--bids-dir",
        required=True,
        type=Path,
        help=(
            "Root BIDS directory containing subject folders sub-<bblid> and per-subject "
            "sessions TSV files sub-<bblid>_sessions.tsv"
        ),
    )
    parser.add_argument(
        "--log-pattern",
        required=False,
        default="*-frac2B_1.00_no1B.log",
        help="Glob pattern for EF log files inside FILES/ (default: %(default)s)",
    )
    parser.add_argument(
        "--datadump-root",
        required=False,
        type=Path,
        default=Path(
            "/cbica/projects/executive_function/task_events_files/original_box_folders/SCANNER_TASK"
        ),
        help=(
            "Root directory that contains SCANNER_TASK_T1/T2/T3 subfolders to search "
            "for missing logs (default: %(default)s)"
        ),
    )
    parser.add_argument(
        "--recovered-acquisition-name",
        required=False,
        default="RECOVERED",
        help=(
            "Name of the acquisition folder to create under ACQUISITIONS when "
            "copying recovered logs (default: %(default)s)"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Do not copy files; just report what would be done. Recovery status "
            "rows will use WOULD_COPY instead of COPIED."
        ),
    )
    parser.add_argument(
        "--report-tsv",
        type=Path,
        help=(
            "If provided, write recovery attempts to this TSV instead of stdout. "
            "Columns: bblid, session_id, status, message, log_path, log_date, expected_date, dest_path"
        ),
    )
    return parser.parse_args()


def discover_logs_flywheel(
    logs_dir: Path, pattern: str
) -> Dict[Tuple[str, str], List[Path]]:
    """
    Discover logs using the Flywheel tree pattern:
      <bblid>/SESSIONS/<scanid>/ACQUISITIONS/*/FILES/<pattern>

    Returns mapping (bblid, scanid) -> list of log paths.
    """
    mapping: Dict[Tuple[str, str], List[Path]] = {}
    for log_path in logs_dir.rglob(pattern):
        if not log_path.is_file():
            continue
        parts = log_path.parts
        if "SESSIONS" not in parts:
            continue
        idx = parts.index("SESSIONS")
        if idx - 1 < 0 or idx + 1 >= len(parts):
            continue
        bblid = parts[idx - 1]
        scanid = parts[idx + 1]
        if not bblid or not scanid:
            continue
        mapping.setdefault((bblid, scanid), []).append(log_path)
    return mapping


def load_session_map(session_map_path: Path) -> Dict[Tuple[str, str], str]:
    df = pd.read_csv(session_map_path, sep="\t")
    required_cols = {"bblid", "scanid", "session_id"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing required columns in session map: {', '.join(sorted(missing))}"
        )
    mapping: Dict[Tuple[str, str], str] = {
        (str(r.bblid), str(r.scanid)): str(r.session_id)
        for r in df.itertuples(index=False)
    }
    return mapping


def load_session_map_with_timestamps(
    session_map_path: Path,
) -> Tuple[
    Dict[Tuple[str, str], str],
    Dict[Tuple[str, str], str],
    Dict[Tuple[str, str], Optional[pd.Timestamp]],
    Dict[Tuple[str, str], Optional[str]],
]:
    """
    Load session map and expose three lookups:
    - (bblid, scanid) -> session_id
    - (bblid, session_id) -> scanid
    - (bblid, session_id) -> timestamp (as pandas Timestamp, optional)
    """
    df = pd.read_csv(session_map_path, sep="\t")
    required_cols = {"bblid", "scanid", "session_id"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing required columns in session map: {', '.join(sorted(missing))}"
        )

    # Normalize types
    df["bblid"] = df["bblid"].astype(str)
    df["scanid"] = df["scanid"].astype(str)
    df["session_id"] = df["session_id"].astype(str)

    # Parse timestamp if present
    timestamp_col = "timestamp" if "timestamp" in df.columns else None
    if timestamp_col:
        with pd.option_context("mode.chained_assignment", None):
            df["_timestamp_parsed"] = pd.to_datetime(
                df[timestamp_col], errors="coerce", utc=True
            )
    else:
        df["_timestamp_parsed"] = pd.NaT

    by_scan: Dict[Tuple[str, str], str] = {}
    scan_by_session: Dict[Tuple[str, str], str] = {}
    timestamp_by_session: Dict[Tuple[str, str], Optional[pd.Timestamp]] = {}
    date_by_session: Dict[Tuple[str, str], Optional[str]] = {}

    def _normalize_session_id(session_id: str) -> str:
        m = re.match(r"ses-(\d+)$", session_id)
        if not m:
            return session_id
        # Remove leading zeros
        try:
            n = int(m.group(1))
            return f"ses-{n}"
        except Exception:
            return session_id

    def _extract_date_str(value: Optional[str]) -> Optional[str]:
        if value is None:
            return None
        s = str(value).strip()
        if len(s) >= 10:
            return s[:10]
        return None

    for r in df.itertuples(index=False):
        key_scan = (str(r.bblid), str(r.scanid))
        ses_id = _normalize_session_id(str(r.session_id))
        by_scan[key_scan] = ses_id
        key_ses = (str(r.bblid), ses_id)
        scan_by_session[key_ses] = str(r.scanid)
        # r._timestamp_parsed may be NaT; store None in that case
        ts_val = getattr(r, "_timestamp_parsed", pd.NaT)
        timestamp_by_session[key_ses] = None if pd.isna(ts_val) else ts_val
        raw_ts = (
            df.loc[
                (df["bblid"] == r.bblid) & (df["session_id"] == r.session_id),
                timestamp_col,
            ].iloc[0]
            if timestamp_col
            else None
        )
        date_by_session[key_ses] = _extract_date_str(raw_ts) if timestamp_col else None

    return by_scan, scan_by_session, timestamp_by_session, date_by_session


def build_subject_session_pairs_with_logs(
    logs_map: Dict[Tuple[str, str], List[Path]],
    ses_map: Dict[Tuple[str, str], str],
) -> Tuple[Set[Tuple[str, str]], Set[Tuple[str, str]]]:
    """
    Return a set of (bblid, session_id) for which logs exist and map is available.
    Also return a set of (bblid, scanid) that had logs but no session mapping.
    """
    pairs: Set[Tuple[str, str]] = set()
    unmapped: Set[Tuple[str, str]] = set()
    for (bblid, scanid), paths in logs_map.items():
        if len(paths) == 0:
            continue
        ses_label = ses_map.get((bblid, scanid))
        if not ses_label:
            unmapped.add((bblid, scanid))
            continue
        pairs.add((bblid, ses_label))
    return pairs, unmapped


def read_bids_subject_session_pairs(
    bids_dir: Path,
) -> Tuple[Set[Tuple[str, str]], Set[str]]:
    """
    Read subject/session pairs from a BIDS dataset by scanning sub-<bblid> folders
    and loading each per-subject sessions TSV at sub-<bblid>/sub-<bblid>_sessions.tsv.
    Returns (pairs, subjects) where pairs is a set of (bblid, session_id) and
    subjects is the set of subject IDs discovered under the BIDS directory.
    """
    pairs: Set[Tuple[str, str]] = set()
    subjects: Set[str] = set()

    if not bids_dir.exists() or not bids_dir.is_dir():
        raise ValueError(
            f"BIDS directory does not exist or is not a directory: {bids_dir}"
        )

    def _normalize_session_id(session_id: str) -> str:
        m = re.match(r"ses-(\d+)$", session_id)
        if not m:
            return session_id
        try:
            n = int(m.group(1))
            return f"ses-{n}"
        except Exception:
            return session_id

    for subj_dir in sorted(bids_dir.iterdir()):
        if not subj_dir.is_dir() or not subj_dir.name.startswith("sub-"):
            continue
        bblid = subj_dir.name.replace("sub-", "")
        subjects.add(bblid)

        sessions_tsv = subj_dir / f"sub-{bblid}_sessions.tsv"
        if not sessions_tsv.exists():
            continue
        try:
            df = pd.read_csv(sessions_tsv, sep="\t")
        except Exception:
            continue
        if "session_id" not in df.columns:
            continue
        for ses in df["session_id"].dropna().astype(str):
            if ses:
                pairs.add((bblid, _normalize_session_id(ses)))
    return pairs, subjects


def _session_id_to_scanner_task_subdir(session_id: str) -> Optional[str]:
    """
    Map ses-id (e.g., ses-1) to SCANNER_TASK_T1/T2/T3 subfolder name.
    Returns None if no mapping can be determined.
    """
    m = re.match(r"ses-(\d+)$", session_id)
    if not m:
        return None
    num = m.group(1)
    return f"SCANNER_TASK_T{num}"


def find_datadump_logs(
    datadump_root: Path,
    bblid: str,
    session_id: str,
    pattern_tail: str,
) -> List[Path]:
    """
    Search under datadump_root/SCANNER_TASK_T{n} recursively for files that match
    <bblid>{pattern_tail} (e.g., <bblid>*-frac2B_1.00_no1B.log).
    """
    subdir = _session_id_to_scanner_task_subdir(session_id)
    if not subdir:
        return []
    base = datadump_root / subdir
    if not base.exists():
        return []
    # Ensure a wildcard between bblid and suffix (e.g., <bblid>*-frac2B_1.00_no1B.log)
    suffix = pattern_tail[1:] if pattern_tail.startswith("*") else pattern_tail
    pattern = f"{bblid}*{suffix}"
    return sorted(p for p in base.rglob(pattern) if p.is_file())


def parse_log_written_datetime(log_path: Path) -> Optional[datetime]:
    """
    Parse the 'Logfile written - mm/dd/YYYY HH:MM:SS' from the second line of a
    .log file. Returns a naive datetime if found; otherwise None.
    """
    try:
        # Read first two lines only
        with log_path.open("r", errors="ignore") as f:
            _ = f.readline()
            line2 = f.readline()
    except Exception:
        return None

    if not line2:
        return None
    m = re.search(
        r"Logfile\s+written\s*-\s*(\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}:\d{2})",
        line2,
    )
    if not m:
        return None
    date_str = m.group(1)
    try:
        return datetime.strptime(date_str, "%m/%d/%Y %H:%M:%S")
    except Exception:
        return None


def copy_log_to_recovered(
    src_log: Path,
    logs_dir: Path,
    bblid: str,
    scanid: str,
    recovered_acq_name: str,
) -> Path:
    """
    Copy src_log under <logs_dir>/<bblid>/SESSIONS/<scanid>/ACQUISITIONS/
    <recovered_acq_name>/FILES/<filename> and return the destination path.
    """
    dest_dir = (
        logs_dir
        / bblid
        / "SESSIONS"
        / scanid
        / "ACQUISITIONS"
        / recovered_acq_name
        / "FILES"
    )
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_path = dest_dir / src_log.name
    shutil.copy2(src_log, dest_path)
    return dest_path


def main() -> int:
    args = parse_args()
    logs_dir: Path = args.logs_dir
    session_map_path: Path = args.session_map
    bids_dir: Path = args.bids_dir
    log_pattern: str = args.log_pattern
    datadump_root: Path = args.datadump_root
    recovered_acq_name: str = args.recovered_acquisition_name
    dry_run: bool = args.dry_run
    report_tsv: Optional[Path] = args.report_tsv

    # Discover logs and load mapping
    logs_map = discover_logs_flywheel(logs_dir, log_pattern)
    by_scan_map, scan_by_session_map, timestamp_by_session_map, date_by_session_map = (
        load_session_map_with_timestamps(session_map_path)
    )
    logs_pairs, unmapped_logs = build_subject_session_pairs_with_logs(
        logs_map, by_scan_map
    )

    # Read BIDS subject/session pairs
    bids_pairs, bids_subjects = read_bids_subject_session_pairs(bids_dir)

    print("=== Overview ===")
    print(f"Logs discovered (unique bblid/scanid): {len(logs_map)}")
    print(f"Session-mapped log pairs (bblid/session): {len(logs_pairs)}")
    print(f"Unmapped logs (no session_id in map): {len(unmapped_logs)}")
    print(f"BIDS subjects: {len(bids_subjects)}")
    print(f"BIDS subject/session pairs: {len(bids_pairs)}")
    print()

    # Session-aware comparison (BIDS always provides sessions via per-subject TSVs)
    only_in_logs = sorted(logs_pairs - bids_pairs)
    only_in_bids = sorted(bids_pairs - logs_pairs)

    print("=== Session-level comparison ===")
    print(f"Pairs with logs but missing in BIDS sessions: {len(only_in_logs)}")
    for bblid, ses in only_in_logs:
        print(f"  {bblid}\t{ses}")
    print()

    print(
        "Pairs present in BIDS sessions but with no logs discovered: "
        f"{len(only_in_bids)}"
    )
    for bblid, ses in only_in_bids:
        print(f"  {bblid}\t{ses}")
    print()

    # Subject-level comparison
    subjects_with_logs = {b for (b, _s) in logs_pairs} if logs_pairs else set()
    only_in_logs_subj = sorted(subjects_with_logs - bids_subjects)
    only_in_bids_subj = sorted(bids_subjects - subjects_with_logs)

    print("=== Subject-level comparison ===")
    print(f"Subjects with logs but missing in BIDS: {len(only_in_logs_subj)}")
    for b in only_in_logs_subj:
        print(f"  {b}")
    print()

    print(
        "Subjects present in BIDS but with no logs discovered: "
        f"{len(only_in_bids_subj)}"
    )
    for b in only_in_bids_subj:
        print(f"  {b}")
    print()

    if unmapped_logs:
        print("=== Logs without session mapping (bblid/scanid) ===")
        for bblid, scanid in sorted(unmapped_logs):
            print(f"  {bblid}\t{scanid}")

    # Attempt recovery for sessions missing logs in the Flywheel tree
    if only_in_bids:
        print()
        print("=== Recovery attempts for missing BIDS sessions ===")
        pattern_tail = (
            log_pattern.replace("*", "", 1)
            if log_pattern.startswith("*")
            else log_pattern
        )
        report_rows: List[Dict[str, str]] = []
        for bblid, ses in only_in_bids:
            key = (bblid, ses)
            expected_ts = timestamp_by_session_map.get(key)
            expected_date_str = date_by_session_map.get(key) or "NA"
            expected_date = None
            if expected_ts is not None and not pd.isna(expected_ts):
                # Compare by date (UTC-aware timestamp in map vs naive log time)
                expected_date = expected_ts.date()
            elif expected_date_str != "NA":
                # Fallback: parse date string directly
                try:
                    expected_date = datetime.strptime(
                        expected_date_str, "%Y-%m-%d"
                    ).date()
                except Exception:
                    expected_date = None

            # We need scanid to construct the destination path
            scanid = scan_by_session_map.get(key)
            if not scanid:
                msg = "no scanid for bblid/ses"
                if report_tsv:
                    report_rows.append(
                        {
                            "bblid": bblid,
                            "session_id": ses,
                            "status": "NO_SESSION_MAP",
                            "message": msg,
                            "log_path": "",
                            "log_date": "",
                            "expected_date": expected_date_str,
                            "dest_path": "",
                        }
                    )
                else:
                    print(f"  {bblid}\t{ses}\tSTATUS=NO_SESSION_MAP\tmsg={msg}")
                continue

            candidates = find_datadump_logs(datadump_root, bblid, ses, pattern_tail)
            if not candidates:
                msg = "no matching log in datadump"
                if report_tsv:
                    report_rows.append(
                        {
                            "bblid": bblid,
                            "session_id": ses,
                            "status": "NOT_FOUND",
                            "message": msg,
                            "log_path": "",
                            "log_date": "",
                            "expected_date": expected_date_str,
                            "dest_path": "",
                        }
                    )
                else:
                    print(f"  {bblid}\t{ses}\tSTATUS=NOT_FOUND\tmsg={msg}")
                continue

            # Parse dates and look for a date match
            matched_path: Optional[Path] = None
            first_date_str: Optional[str] = None
            for p in candidates:
                dt_val = parse_log_written_datetime(p)
                if dt_val is None:
                    continue
                if first_date_str is None:
                    first_date_str = dt_val.strftime("%Y-%m-%d")
                if expected_date is not None and dt_val.date() == expected_date:
                    matched_path = p
                    break

            if matched_path is None:
                # No date-matching candidate
                example = candidates[0]
                example_dt = parse_log_written_datetime(example)
                example_dt_str = example_dt.strftime("%Y-%m-%d") if example_dt else "NA"
                if report_tsv:
                    report_rows.append(
                        {
                            "bblid": bblid,
                            "session_id": ses,
                            "status": "FOUND_DATE_MISMATCH",
                            "message": "",
                            "log_path": str(example),
                            "log_date": example_dt_str,
                            "expected_date": expected_date_str,
                            "dest_path": "",
                        }
                    )
                else:
                    print(
                        f"  {bblid}\t{ses}\tSTATUS=FOUND_DATE_MISMATCH\tlog={example}\tlog_date={example_dt_str}\texpected_date={expected_date_str}"
                    )
                continue

            # Copy recovered file
            try:
                dest = (
                    logs_dir
                    / bblid
                    / "SESSIONS"
                    / scanid
                    / "ACQUISITIONS"
                    / recovered_acq_name
                    / "FILES"
                    / matched_path.name
                )
                if dry_run:
                    status = "WOULD_COPY"
                else:
                    dest = copy_log_to_recovered(
                        matched_path, logs_dir, bblid, scanid, recovered_acq_name
                    )
                    status = "COPIED"
                if report_tsv:
                    report_rows.append(
                        {
                            "bblid": bblid,
                            "session_id": ses,
                            "status": status,
                            "message": "",
                            "log_path": str(matched_path),
                            "log_date": expected_date_str,
                            "expected_date": expected_date_str,
                            "dest_path": str(dest),
                        }
                    )
                else:
                    print(
                        f"  {bblid}\t{ses}\tSTATUS={status}\tsrc={matched_path}\tdst={dest}"
                    )
            except Exception as e:
                if report_tsv:
                    report_rows.append(
                        {
                            "bblid": bblid,
                            "session_id": ses,
                            "status": "COPY_FAILED",
                            "message": str(e),
                            "log_path": str(matched_path) if matched_path else "",
                            "log_date": "",
                            "expected_date": expected_date_str,
                            "dest_path": "",
                        }
                    )
                else:
                    print(
                        f"  {bblid}\t{ses}\tSTATUS=COPY_FAILED\tsrc={matched_path}\tmsg={e}"
                    )

        # If requested, write TSV report
        if report_tsv:
            import csv

            fieldnames = [
                "bblid",
                "session_id",
                "status",
                "message",
                "log_path",
                "log_date",
                "expected_date",
                "dest_path",
            ]
            report_tsv.parent.mkdir(parents=True, exist_ok=True)
            with report_tsv.open("w", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
                writer.writeheader()
                writer.writerows(report_rows)
            print(f"Wrote recovery report TSV: {report_tsv}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
