# Define the input datasets
input_datasets:
    BIDS:
        required_files:
            - "perf/*_asl.nii*"
            - "anat/*_T1w.nii*"
        is_zipped: false
        origin_url: "/cbica/projects/executive_function/data/bids/EF_bids_data_DataLad"
        path_in_babs: inputs/data/BIDS
    fmriprep_anat:
        required_files:
            - "*fmriprep_anat*.zip"
        is_zipped: true
        origin_url: "ria+file:///cbica/projects/executive_function/EF_dataset/derivatives/fmriprepANAT_BABS_EF_full_project/output_ria#~data"
        path_in_babs: inputs/data/fmriprep_anat

# Arguments in `singularity run`:
bids_app_args:
    $SUBJECT_SELECTION_FLAG: "--participant-label"
    -w: "$BABS_TMPDIR" # this is a placeholder recognized by BABS.
    --nprocs: "8"
    --omp-nthreads: "8"
    --mem-mb: "30000"
    --stop-on-first-crash: ""
    --fs-license-file: "/cbica/software/external/freesurfer/centos7/5.3.0/license.txt" # [FIX ME] path to FreeSurfer license file
    --skip-bids-validation: ""
    --output-spaces: "MNI152NLin6Asym:res-2"
    -v: "-v"
    --m0_scale: "10"
    --level: "full"
    --scorescrub: ""
    --basil: ""
    --cifti-output: "91k"
    --project-goodvoxels: ""
    --fs-no-resume: ""
    --fs-subjects-dir: "${PWD}/inputs/data/fmriprep_anat/fmriprep_anat/sourcedata/freesurfer"

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
#   As ASLPrep will use BIDS output layout, we need to ask BABS to create a folder 'aslprep' to wrap all derivatives:
all_results_in_one_zip: true
zip_foldernames:
    aslprep: "0-7-5" # folder 'aslprep' will be zipped into 'sub-xx_(ses-yy_)aslprep-0-7-5.zip'

# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: "/bin/bash"
    hard_memory_limit: 60G
    temporary_disk_space: 200G
    hard_runtime_limit: "7:00:00"
    customized_text: |
        #SBATCH -p all
        #SBATCH --nodes=1
        #SBATCH --ntasks=1
        #SBATCH --cpus-per-task=8
        #SBATCH --mem=32G
        #SBATCH --propagate=NONE

# Arguments that are passed directly to singularity/apptainer:
singularity_args:
    - --containall
    - --writable-tmpfs
    - -B ${PWD}/.git/tmp/wkdir:/tmp 

# Necessary commands to be run first:
#   [FIX ME] change or add commands for setting up the virtual environment, for loading necessary modules, etc
script_preamble: |
    eval "$(micromamba shell hook --shell bash)"
    micromamba activate babs

# Where to run the jobs:
job_compute_space: "${TMP}" # [FIX ME] replace "/path/to/temporary_compute_space" with yours

# Alert messages that might be found in log files of failed jobs:
#   These messages may be helpful for debugging errors in failed jobs.
alert_log_messages:
    stdout:
        - "Excessive topologic defect encountered"
        - "Cannot allocate memory"
        - "mris_curvature_stats: Could not open file"
        - "Numerical result out of range"
        - "ASLPrep failed"
