---
title: "EF_demographics_updated"
output: html_document
date: "2025-07-10"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(dplyr)
```


```{r clean original demographics csv file}
# Read the demographics CSV file
demographic_data <- read.csv("/Users/bsevchik/projects/EF_clinical/demographics/efr_demographics_original.csv")
demographic_data

# Read participants_scanned csv
participants_scanned_df <- read.csv('/Users/bsevchik/projects/EF_clinical/participants.csv')
participants_scanned_df$participant_id <- sub("sub-", "", participants_scanned_df$participant_id) #get rid of sub- prefix
participants_scanned_df$participant_id <- as.integer(participants_scanned_df$participant_id) #make sure it counts as an integer


# Convert age to years and remove duplicates by keeping the first session, the row with the lowest age_intake
demographic_data <- demographic_data %>%
  group_by(participant_id) %>%
  filter(age_intake == min(age_intake)) %>%
  ungroup %>%
  rename(age_months = age_intake) %>%
  mutate(age = floor(age_months / 12))
demographic_data


# Only include subjects that were scanned
demographic_data_scanned <- demographic_data %>%
  filter(participant_id %in% participants_scanned_df$participant_id)
demographic_data_scanned
write.csv(demographic_data_scanned, "/Users/bsevchik/projects/EF_clinical/demographics/demographics_data_scanned.csv", row.names = FALSE)



```

```{r edit study groups to be correct}
# change study groups that were wrong in both demographic data & clinical diagnostic data
UPDATED_demographic_data_scanned <- demographic_data_scanned %>%
  mutate(
    study_group = case_when(
      participant_id %in% c(20333, 20410, 20533, 20724, 20818, 20842, 20866, 20902, 20983, 21035, 21050, 21139, 21161, 21856, 23303, 21197) ~ "PRO/CHR",
      TRUE ~ study_group
    )
  )
UPDATED_demographic_data_scanned

# have to do this again bc some additional subjects wrong in demographic data but not wrong in clinical diagnostic data - confirmed with Oracle search
UPDATED_demographic_data_scanned <- UPDATED_demographic_data_scanned %>%
  mutate(
    study_group = case_when(
      participant_id %in% c(21712, 22520) ~ "PRO/CHR",
      participant_id %in% c(20236) ~ 'ADHD',
      TRUE ~ study_group
    )
  )
UPDATED_demographic_data_scanned

write.csv(UPDATED_demographic_data_scanned, "/Users/bsevchik/projects/EF_clinical/demographics/UPDATED_demographic_data_scanned.csv", row.names = FALSE)



```
UPDATED_demographic_data_scanned is the final csv file. This contains fixed study groups as well, and only participants that were actually scanned as well.







######


```{r demographic tables}
# Table 1: Diagnosis 
diagnosis_table <- UPDATED_demographic_data_scanned %>%
  mutate(study_group = if_else(is.na(study_group), "N/A", study_group)) %>%
  count(study_group, name = "n") %>%
  mutate(percent = round((n / sum(n)) * 100, 1))
diagnosis_table

# Table 2: Sex
sex_table <- UPDATED_demographic_data_scanned %>%
  mutate(sex = if_else(is.na(sex), "N/A", sex)) %>%
  count(sex, name = "n") %>%
  mutate(percent = round((n / sum(n)) * 100, 1))
sex_table

# Table 3: Hispanic vs. Non-Hispanic
ethnicity_table <- UPDATED_demographic_data_scanned %>%
  mutate(ethnicity = if_else(is.na(ethnicity), "N/A", ethnicity)) %>%
  count(ethnicity, name = "n") %>%
  mutate(percent = round((n / sum(n)) * 100, 1))
ethnicity_table

# Table 4: Race
race_table <- UPDATED_demographic_data_scanned %>%
  mutate(race = if_else(is.na(race), "N/A", race)) %>%
  count(race, name = "n") %>%
  mutate(percent = round((n / sum(n)) * 100, 1))
race_table

# Table 5: Age
age_range <- range(UPDATED_demographic_data_scanned$age)
age_mean <- mean(UPDATED_demographic_data_scanned$age)
print(age_range)
print(age_mean)
```


```{r pie charts}
# Diagnosis Pie Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/diagnosis_pie_chart.png", 
    width = 3000, height = 2000, res = 300)

diagnosis_pie_chart <- ggplot(diagnosis_table, aes(x = "", y = n, fill = study_group)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Diagnosis", fill = "Diagnosis") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_label_repel(aes(label = paste0(round(percent, 1), "%")),
                   position = position_stack(vjust = 0.5),
                   size = 4,  # Keep text readable
                   box.padding = 0.5,  # Adds space around text to prevent overlap
                   point.padding = 0.3, 
                   direction = "both", # Allows free movement
                   show.legend = FALSE) + # Removes extra label in legend
  scale_fill_manual(values = c("ADHD" = "#B6A6E9", "PRO/CHR" = "#4394E5", "TD/NC" = "#AFDC8F", "Unknown" = "#F8AE54")) +
guides(fill = guide_legend(title = NULL))  # Removes the legend title
diagnosis_pie_chart

print(diagnosis_pie_chart)
dev.off()

# Sex Pie Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/sex_pie_chart.png", 
    width = 3000, height = 2000, res = 300)

sex_pie_chart <- ggplot(sex_table, aes(x = "", y = n, fill = sex)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Sex", fill = "Sex") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_label_repel(aes(label = paste0(round(percent, 1), "%")),
                   position = position_stack(vjust = 0.5),
                   size = 4,  # Keep text readable
                   box.padding = 0.5,  # Adds space around text to prevent overlap
                   point.padding = 0.3, 
                   direction = "both", # Allows free movement
                   show.legend = FALSE) +  # Removes extra label in legend
  scale_fill_manual(values = c("M" = "#B6A6E9", "F" = "#4394E5")) +
  guides(fill = guide_legend(title = NULL))  # Removes the legend title
sex_pie_chart
print(sex_pie_chart)
dev.off()


# Ethnicity Pie Chart
#ethnicity_pie_chart <- ggplot(ethnicity_table, aes(x = "", y = n, fill = ethnic)) +
  #geom_bar(width = 1, stat = "identity") +
  #coord_polar("y", start = 0) +
  #labs(title = "Ethnicity", fill = "Ethnic") +
  #theme_void() +
  #theme(plot.title = element_text(hjust = 0.5)) +
  #geom_text(aes(label = paste0(round(percent, 1), "%")),
            #position = position_stack(vjust = 0.5))
#ethnicity_pie_chart


# Ethnicity Pie Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/ethnicity_pie_chart.png", 
    width = 3000, height = 2000, res = 300)

ethnicity_pie_chart <- ggplot(ethnicity_table, aes(x = "", y = n, fill = ethnicity)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Ethnicity", fill = "Ethnicity") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_label_repel(aes(label = paste0(round(percent, 1), "%")),
                   position = position_stack(vjust = 0.5),
                   size = 4,  # Keep text readable
                   box.padding = 0.5,  # Adds space around text to prevent overlap
                   point.padding = 0.3, 
                   direction = "both", # Allows free movement
                   show.legend = FALSE) +  # Removes extra label in legend
   scale_fill_manual(values = c("Hispanic" = "#B6A6E9", "N/A" = "#4394E5", "Non - Hispanic" = "#AFDC8F")) +
  guides(fill = guide_legend(title = NULL))  # Removes the legend title
ethnicity_pie_chart
print(ethnicity_pie_chart)
dev.off()


# Race pie chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/race_pie_chart.png", 
    width = 3000, height = 2000, res = 300)

race_pie_chart <- ggplot(race_table, aes(x = "", y = n, fill = race)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Race", fill = "Race") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_label_repel(aes(label = paste0(round(percent, 1), "%")),
                   position = position_stack(vjust = 0.5),
                   size = 4,  # Keep text readable
                   box.padding = 0.5,  # Adds space around text to prevent overlap
                   point.padding = 0.3, 
                   direction = "both", # Allows free movement
                   show.legend = FALSE) +  # Removes extra label in legend
   scale_fill_manual(values = c("Asian" = "#B6A6E9", "Black or African American" = "#4394E5", "More than one race" = "#AFDC8F", "Unknown or not reported" = "#F8AE54", "White" = "#92C5F9")) +
  guides(fill = guide_legend(title = NULL))  # Removes the legend title
race_pie_chart
print(race_pie_chart)
dev.off()

```

```{r bar charts}

# Diagnosis Bar Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/diagnosis_bar_chart.png", 
    width = 2000, height = 2000, res = 300)

ggplot(diagnosis_table, aes(x = reorder(study_group, -percent), y = percent, fill = study_group)) +
  geom_col() +
  geom_text(aes(label = paste0(percent, "%")), vjust = -0.3, size = 5) +
  labs(title = "Diagnosis Distribution", x = "Study Group", y = "Percent", fill = "Study Group") +
  theme_minimal(base_size = 20) +
  scale_fill_manual(values = c("ADHD" = "#B6A6E9", "PRO/CHR" = "#4394E5", "TD/NC" = "#AFDC8F", "Unknown" = "#F8AE54")) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )

dev.off()


# Sex Bar Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/sex_bar_chart.png", 
    width = 2000, height = 2000, res = 300)

ggplot(sex_table, aes(x = sex, y = percent, fill = sex)) +
  geom_col() +
  geom_text(aes(label = paste0(percent, "%")), vjust = -0.3, size = 5) +
  labs(title = "Sex Distribution", x = "Sex", y = "Percent", fill = "Sex") +
  theme_minimal(base_size = 20) +
  scale_fill_manual(values = c("M" = "#B6A6E9", "F" = "#4394E5")) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )

dev.off()


# Ethnicity Bar Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/ethnicity_bar_chart.png", 
    width = 2000, height = 2000, res = 300)

ggplot(ethnicity_table, aes(x = ethnicity, y = percent, fill = ethnicity)) +
  geom_col() +
  geom_text(aes(label = paste0(percent, "%")), vjust = -0.3, size = 5) +
  labs(title = "Ethnicity Distribution", x = "Ethnicity", y = "Percent", fill = "Ethnicity") +
  theme_minimal(base_size = 20) +
  scale_fill_manual(values = c("Hispanic" = "#B6A6E9", "N/A" = "#4394E5", "Non - Hispanic" = "#AFDC8F")) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )

dev.off()


# Race Bar Chart
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/race_bar_chart.png", 
    width = 3000, height = 2000, res = 300)

ggplot(race_table, aes(x = reorder(race, -percent), y = percent, fill = race)) +
  geom_col() +
  geom_text(aes(label = paste0(percent, "%")), vjust = -0.3, size = 5) +
  labs(title = "Race Distribution", x = "Race", y = "Percent", fill = "Race") +
  theme_minimal(base_size = 20) +
  scale_fill_manual(values = c(
    "Asian" = "#B6A6E9", 
    "Black or African American" = "#4394E5", 
    "More than one race" = "#AFDC8F", 
    "Unknown or not reported" = "#F8AE54", 
    "White" = "#92C5F9"
  )) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )

dev.off()



```



```{r stacked bar chart example}
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/race_diagnosis_bar_chart.png", 
    width = 3000, height = 2000, res = 300)

race_diagnosis_bar_chart <- UPDATED_demographic_data_scanned %>%
  count(study_group, race) %>%
  group_by(study_group) %>%
  mutate(percent = (n / sum(n)) * 100) %>%
  ggplot(aes(x = study_group, y = percent, fill = race)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +  # Convert to percentage
  labs(title = "Race Distribution by Study Group", x = "Group", y = "Percentage") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c("Asian" = "#B6A6E9", "Black or African American" = "#4394E5", "More than one race" = "#AFDC8F", "Unknown or not reported" = "#F8AE54", "White" = "#92C5F9")) +
  geom_text(aes(label = paste0(round(percent, 1), "%")), 
            position = position_fill(vjust = 0.5), size = 3.5, color = "black")
race_diagnosis_bar_chart
print(race_diagnosis_bar_chart)
dev.off()
```

```{r violin plot for age}
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/age_violin_plot.png", 
    width = 3000, height = 2000, res = 300)

# Create the violin plot with jittered points
age_violin_plot <- ggplot(UPDATED_demographic_data_scanned, aes(x = "", y = age)) +
  geom_violin(fill = "#92C5F9", color = "black", alpha = 0.7) +  # Violin plot
  geom_boxplot(width = 0.1, fill = "white", outlier.shape = NA) +  # Boxplot inside violin
  geom_jitter(width = 0.1, color = "black", size = 1.5, alpha = 0.6) +  # Individual points
  labs(title = "Age Distribution of Study Sample at Intake",
       y = "Age",
       x = "") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
age_violin_plot
print(age_violin_plot)
dev.off()


png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/age_histogram.png", 
    width = 3000, height = 2000, res = 300)
# Histogram for age
age_histogram <- ggplot(UPDATED_demographic_data_scanned, aes(x = age)) +
  geom_histogram(binwidth = 5, fill = "steelblue", color = "white") +
  labs(title = "Histogram of Ages", x = "Age", y = "Count") +
  theme_minimal()
age_histogram
print(age_histogram)
dev.off()


```


```{r histogram for age}
png(filename = "/Users/bsevchik/projects/EF_clinical/demographics/age_histogram.png", 
    width = 2300, height = 2000, res = 300, bg = "transparent")

age_histogram <- ggplot(demographic_data, aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "#92C5F9", color = "black", alpha = 0.9) +
  labs(title = "Age Distribution",
       x = "Age (Years)",
       y = "Count") +
  theme_minimal(base_size = 20) +
  theme(
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )

print(age_histogram)
dev.off()
```


















